version: '3'
services:
  react:
    build:
      context: "klicker-react"
      args:
        API_URL: "http://localhost:4000/graphql"
        APP_FINGERPRINTING: "true"
    environment:
      NODE_ENV: "production"
      REDIS_URL: "redis"
      STATIC_PATH: "/"
    ports:
      - "3000:3000"

  api:
    build: "klicker-api"
    ports:
      - "4000:3000"
    environment:
      APP_DOMAIN: "localhost"
      APP_SECRET: "hello-world"
      MONGO_URL: "mongodb/klicker"
      NODE_ENV: "production"
      ORIGIN: "http://localhost:3000"
      PORT: 3000
      REDIS_URL: "redis"

  redis:
    image: "redis:3-32bit"
    ports:
      - "6379:6379"

  mongodb:
    image: "mongo:3.2"
    ports:
      - "27017:27017"
